package com.app.confeitaria.docelivery.model.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Permission {

    ADMIN_READ("ADMIN_READ"),
    ADMIN_UPDATE("ADMIN_UPDATE"),
    ADMIN_CREATE("ADMIN_CREATE"),
    ADMIN_DELETE("ADMIN_DELETE"),

    CONFEITEIRO_READ("CONFEITEIRO_READ"),
    CONFEITEIRO_UPDATE("CONFEITEIRO_UPDATE"),
    CONFEITEIRO_CREATE("CONFEITEIRO_CREATE"),
    CONFEITEIRO_DELETE("CONFEITEIRO_DELETE"),

    CLIENTE_READ("CLIENTE_READ"),
    CLIENTE_UPDATE("CLIENTE_UPDATE"),
    CLIENTE_CREATE("CLIENTE_CREATE"),
    CLIENTE_DELETE("CLIENTE_DELETE"),

    ENTREGADOR_READ("ENTREGADOR_READ"),
    ENTREGADOR_UPDATE("ENTREGADOR_UPDATE"),
    ENTREGADOR_CREATE("ENTREGADOR_CREATE"),
    ENTREGADOR_DELETE("ENTREGADOR_DELETE");

    private final String permission;



}
